export const MEDICAL_TERMS: Record<string, string> = {
  'CBNAAT': 'Cartridge Based Nucleic Acid Amplification Test: A rapid, automated molecular diagnostic test for TB.',
  'Xpert MTB/RIF': 'A molecular test that detects Mycobacterium tuberculosis complex DNA and resistance to rifampicin.',
  'Smear Microscopy': 'A diagnostic test to detect acid-fast bacilli (AFB) in sputum samples.',
  'HRZE': 'Standard 1st line anti-TB treatment regimen consisting of Isoniazid, Rifampicin, Pyrazinamide, and Ethambutol.',
  'Drug-Resistant TB': 'TB strains that do not respond to standard anti-TB drugs, requiring more complex regimens.',
  'Hemoptysis': 'The coughing up of blood or blood-stained sputum from the bronchi, larynx, trachea, or lungs.',
  'Lymphadenopathy': 'Disease of the lymph nodes, in which they are abnormal in size, number, or consistency.',
  'Rifampicin': 'A powerful antibiotic used as a first-line treatment for tuberculosis.',
  'Isoniazid': 'A first-line medication for the treatment of tuberculosis.',
  'Pyrazinamide': 'A medication used to treat tuberculosis.',
  'Ethambutol': 'A medication used to treat tuberculosis.',
  'MDR-TB': 'Multidrug-resistant TB, defined as resistance to at least isoniazid and rifampicin.',
  'XDR-TB': 'Extensively drug-resistant TB, defined as resistance to isoniazid and rifampicin, plus any fluoroquinolone and at least one of three second-line injectable drugs.',
};
